apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      Configmap containing user customizable cronjob schedule
data:
  cron-expression: "30 4 * * *" # Default schedule is once per day at 4:30am. Users may configure this value to their liking.